version: "3"

services:
  backend-service:
    build:
      context: .
      dockerfile: dockerfile
    image: webapp-be
    container_name: backend-service
    command: npm run server
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
  frontend-service:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: webapp-fe
    container_name: frontend-service
    command: npm run dev
    env_file: ./frontend/.env
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=pk_test_cGxlYXNpbmctd3Jlbi00My5jbGVyay5hY2NvdW50cy5kZXYk
    volumes:
      - ./frontend/:/usr/app/
    depends_on:
      - backend-service
    ports:
      - "5173:5173"
