version: "3"

services:
  backend-service:
    build:
      context: .
      dockerfile: dockerfile
    image: webapp-be
    container_name: backend-service
    command: npm start
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    networks:
      - backend
      - frontend
  frontend-service:
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: webapp-fe
    container_name: frontend-service
    command: nginx -g 'daemon off;'
    env_file: ./frontend/.env
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=pk_test_cGxlYXNpbmctd3Jlbi00My5jbGVyay5hY2NvdW50cy5kZXYk
    volumes:
      - ./frontend/:/usr/app/
    depends_on:
      - backend-service
    ports:
      - "80:80"
    networks:
      - frontend

networks:
  backend:
  frontend:
